---
- name: get brew path
  shell: 'which brew'
  register: usr_local_bin_brew
  changed_when: False
  sudo: no

- name: install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: usr_local_bin_brew.stdout.find('/usr/local/bin/brew') == -1

- name: install packages
  homebrew: state=latest update_homebrew=yes name=
  with_items:
    - git
    - zsh
    - mercurial
    - bazaar
    - caskroom/cask/brew-cask
    - postgresql
    - memcached
    - redis
    - go
    - elixir
    - hub
    - ssh-copy-id
    - libyubikey
    - yubico-piv-tool
    - ykpers
    - ykclient


- name: install apps
  homebrew_cask: state=present name=
  with_items:
    - google-chrome
    - rubymine
    - clion
    - vlc
    - pycharm-ce
    - intellij-idea-ce
    - microsoft-office-365
    - atom
    - hipchat
    - slack
    - iterm2
    - virtualbox
    - vmware-fusion
    - gpgtools
    - github-desktop
    - sourcetree
    - firefox
    - android-studio
    - yubico-manager
    - yubikey-neo-manager
    - yubikey-personalization-gui
    - yubikey-piv-manager

- name: get default shell
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: False
  sudo: no

- name: ensure zsh is the default shell
  shell:  chsh -s /usr/local/bin/zsh
  when: default_shell.stdout.find('/usr/local/bin/zsh') == -1
