---
- name: add repositories for additional packages
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'ppa:webupd8team/java'
    - 'ppa:zeal-developers/ppa'
    - 'ppa:privacyidea/privacyidea'
    - 'ppa:yubico/stable'

- name: accept Java EULA
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: ensure required pacakages are installed
  apt: pkg={{ item }}
  with_items:
    - zsh
    - tmux
    - vim-gtk
    - ssh
    - ruby-full
    - ruby-dev
    - git
    - bzr
    - mercurial
    - build-essential
    - bison
    - wget
    - curl
    - python-software-properties
    - zeal
    - oracle-java8-installer
    - oracle-java8-set-default
    - gnupg
    - gnupg-agent
    - gpgsm
    - yubikey-luks
    - yubikey-personalization
    - yubikey-personalization-gui
    - yubikey-neo-manager
    - yubico-piv-tool
    - ykneomgr
    - yubikey-piv-manager
    - libyubikey-dev
    - libyubikey0


- name: get default shell
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: False
  sudo: no

- name: ensure zsh is the default shell
  shell:  chsh -s /bin/zsh
  when: default_shell.stdout.find('/bin/zsh') == -1

- stat: path=/usr/bin/docker
  register: docker

- name: install docker
  shell: wget -qO- https://get.docker.com/ | sh
  when: docker.stat.exists == False

- name: ensure {{ user }} is in the docker group
  user: name={{ user }} append=yes groups=docker

- get_url: url=https://download.jetbrains.com/cpp/clion-1.1.1.tar.gz dest=/tmp/clion.tgz validate_certs=False

- name: install clion 1.1.1
  sudo: True
  unarchive: src=/tmp/clion.tgz dest=/opt copy=no

- name: stat clion-1.1.1
  stat: path=/opt/clion-1.1.1
  register: clion

- name: Move clion-1.1.1 to clion
  command: mv /opt/clion-1.1.1 /opt/clion
  when: clion.stat.exists

- file: path=/opt/clion owner={{ user }} recurse=yes
  sudo: True

- copy: src=jetbrains-clion.desktop dest=/usr/share/applications/jetbrains-clion.desktop
  sudo: True

- shell: xdg-desktop-menu forceupdate
  sudo: True

- get_url: url=https://download.jetbrains.com/ruby/RubyMine-7.1.4.tar.gz dest=/tmp/rubymine.tgz validate_certs=False

- name: install rubymine 7.1.4
  sudo: True
  unarchive: src=/tmp/rubymine.tgz dest=/opt copy=no

- name: stat rubymine-7.1.4
  stat: path=/opt/RubyMine-7.1.4
  register: rubymine

- name: Move rubymine-7.1.4 to rubymine
  command: mv /opt/RubyMine-7.1.4 /opt/rubymine
  when: rubymine.stat.exists

- file: path=/opt/rubymine owner={{ user }} recurse=yes
  sudo: True

- copy: src=jetbrains-rubymine.desktop dest=/usr/share/applications/jetbrains-rubymine.desktop
  sudo: True

- shell: xdg-desktop-menu forceupdate
  sudo: True
