---
- name: add repositories for additional packages
  apt_repository: repo=
  with_items:
    - 'ppa:webupd8team/java'
    - 'ppa:zeal-developers/ppa'
    - 'ppa:privacyidea/privacyidea'
    - 'ppa:yubico/stable'

- name: accept Java EULA
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: ensure required pacakages are installed
  apt: pkg=
  with_items:
    - zsh
    - tmux
    - vim-gtk
    - ssh
    - ruby
    - ruby-dev
    - rubygems
    - git
    - bzr
    - mercurial
    - build-essential
    - bison
    - wget
    - curl
    - python-software-properties
    - zeal
    - oracle-java8-installer
    - oracle-java8-set-default
    - gnupg
    - gnupg-agent
    - gpgsm
    - yubikey-luks
    - yubikey-personalization
    - yubikey-personalization-gui
    - yubikey-neo-manager
    - yubico-piv-tool
    - ykneomgr
    - yubikey-piv-manager
    - libyubikey-dev
    - libyubikey0


- name: get default shell
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: False
  sudo: no

- name: ensure zsh is the default shell
  shell:  chsh -s /bin/zsh
  when: default_shell.stdout.find('/bin/zsh') == -1

- stat: path=/usr/bin/docker
  register: docker

- name: install docker
  shell: wget -qO- https://get.docker.com/ | sh
  when: docker.stat.exists == False

- name: ensure {{ user }} is in the docker group
  user: name={{ user }} append=yes groups=docker

- stat: path=/opt/clion
  register: clion

- name: install clion 1.1.1
  sudo: True
  unarchive: src=https://download.jetbrains.com/cpp/clion-1.1.1.tar.gz dest=/opt/clion copy=no
  file: path=/opt/clion owner={{ user }} recurse=yes
  copy: src=shared/jetbrains-clion.desktop dest=/usr/share/applications/jetbrains-clion.desktop
  shell: xdg-desktop-menu forceupdate
  when: clion.stat.exists == False

- stat: path=/opt/rubymine
  register: rubymine

- name: install rubymine 7.1.4
  sudo: True
  unarchive: src=https://download.jetbrains.com/ruby/RubyMine-7.1.4.tar.gz dest=/opt/rubymine copy=no
  file: path=/opt/rubymine owner={{ user }} recurse=yes
  copy: src=shared/jetbrains-rubymine.desktop dest=/usr/share/applications/jetbrains-rubymine.desktop
  shell: xdg-desktop-menu forceupdate
  when: rubymine.stat.exists == False
